const path = require("path");
const fs = require("fs-extra");
const { exec } = require("child_process");
const { glob } = require("glob");

async function buildAPK(buildFolder) {

    console.log("🚀 Starting APK Build...");

    const androidFolder = path.join(buildFolder, "android");

    return new Promise((resolve, reject) => {

        // Cross-platform: gradlew.bat on Windows, ./gradlew on Linux/macOS
        const isWindows = process.platform === "win32";
        const gradleCommand = isWindows ? "gradlew.bat" : "./gradlew";

        // Ensure the wrapper is executable on POSIX systems
        if (!isWindows) {
            try { fs.chmodSync(path.join(androidFolder, "gradlew"), 0o755); } catch {}
        }

        exec(
        `${gradleCommand} assembleRelease --no-daemon`,
            {
                cwd: androidFolder,
                timeout: 1200000,  // 20 minutes timeout
                maxBuffer: 16 * 1024 * 1024, // Gradle logs can be large
                env: { ...process.env, CI: "true" }
            },
            async (error, stdout, stderr) => {

                console.log(stdout);

                if (error) {
                    console.error("❌ Gradle Build Error:");
                    console.error(stderr);
                    return reject(error);
                }

                // Dynamically find the APK (glob, not hardcoded path)
                const apkCandidates = await glob("**/*.apk", {
                    cwd: androidFolder,
                    ignore: ["**/unsigned/**", "**/unaligned/**"]
                });

                if (apkCandidates.length === 0) {
                    return reject(new Error("No APK generated by Gradle"));
                }

                // Prefer release builds, fallback to first found
                let generatedAPK = apkCandidates.find(f => f.includes("release"));
                if (!generatedAPK) {
                    generatedAPK = apkCandidates[0];
                    console.warn("⚠️ No release APK found, using first APK:", generatedAPK);
                } else {
                    console.log("Found release APK:", generatedAPK);
                }

                const fullApkPath = path.join(androidFolder, generatedAPK);

                const outputFolder = path.join(
                    buildFolder,
                    "output"
                );

                await fs.ensureDir(outputFolder);

                const finalAPK = path.join(
                    outputFolder,
                    "app.apk"
                );

                await fs.copy(fullApkPath, finalAPK);

                console.log("✅ APK Built Successfully");
                console.log("📱 APK Location:", finalAPK);

                resolve(finalAPK);

            }
        );

    });

}

module.exports = {
    buildAPK
};